# Generated by Django 5.0.1 on 2024-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEFCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.IntegerField()),
                ('end_range', models.IntegerField()),
                ('operator', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['start_range', 'end_range'], name='locator_def_start_r_f6c9cd_idx')],
            },
        ),
    ]
