# Generated by Django 5.0.1 on 2024-02-05 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='defcode',
            name='locator_def_start_r_f6c9cd_idx',
        ),
        migrations.AddField(
            model_name='defcode',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='defcode',
            index=models.Index(fields=['code', 'start_range', 'end_range'], name='locator_def_code_c1ecbb_idx'),
        ),
    ]
